### ISSUE TITLE
Geography quiz is never-ending, chinese news translations have problems and when you click the 'more' button for more pages on topnav when you are on an iPhone, the more button and the searchbutton smoosh together.

### ISSUE THREAD

**Issue by MaxLi3** [banana-news/reports#16]
Look at the title

**Comment by albertkemp** [comment]
I think those issues can easily be fixed but what do you mean by “chinese news translations have problems”? Do you mean with the actual code or just errors in the writing. Because if it’s no.2 I think you can totally fix that. I’ll try and fix the issues about the buttons and geography quiz, though.

**Comment by albertkemp** [comment]
Uh oh. I think I might not have fixed it:
<img width="601" alt="Screenshot 2024-07-18 at 11 44 26" src="https://github.com/user-attachments/assets/d9da9ad9-4f33-4122-87b5-21600a27c8a4">

**Comment by albertkemp** [comment]
<img width="650" alt="Screenshot 2024-07-20 at 08 26 31" src="https://github.com/user-attachments/assets/66ff2061-709c-41b1-bf9c-f5a2d6d48915">
No, geography quiz is functioning correctly. It will re ask you the ones you got wrong but I can fix that if you want me to - I know how.
